#!/bin/bash
#secureweb, needs "sandbox" from policycoreutils-python and "seunshare" from policycoreutils-sandbox; libflashplayer.so must be placed under /opt (obtainable from adobe website, by downloading flash .tar.gz package)
if [ -a $HOME/.secureweb ]; then rm -fr $(cat $HOME/.secureweb); fi
randomname=".$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)"
echo $randomname > $HOME/.secureweb
mkdir -p $HOME/$randomname/.mozilla/plugins
cp /opt/libflashplayer.so $HOME/$randomname/.mozilla/plugins/libflashplayer.so
sandbox -H $HOME/$randomname -X -t sandbox_web_t firefox $1 && rm -fr $HOME/$randomname
